- name: install apache2 and php 
  tags: apache, httpd, php
  package: 
    name:
      - "{{apache_package_name}}"
      - "{{php_package_name}}"
    state: latest
#  when: ansible_distribution in ["Ubuntu", "Debian"]

# - name: install apache2 on centos
#   tags: apache,centos,httpd
#   ansible.builtin.yum:
#     name:
#       - httpd
#       - php
#     state: latest
#     use_backend: yum3
#   when: ansible_distribution in ["CentOS"] and ansible_distribution_major_version == "7"

- name: start and enable apache service
  tags: apache,httpd
  ansible.builtin.service:
    name: "{{apache_service}}"
    state: started
    enabled: yes
#  when: ansible_distribution == "CentOS"

# - name: start apache2 on centos
#   ansible.builtin.service:
#     name: httpd
#     state: started
#   when: ansible_distribution == "CentOS"

- name: configure firewall on centos
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    port: 80/tcp
    state: enabled
  when: ansible_distribution in ["CentOS"]

- name: change email address for admin
  tags: apache,centos,httpd
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: '^ServerAdmin'
    line: ServerAdmin dwaynibaby@baby.com
  when: ansible_distribution == "CentOS"
  notify: 
    - restart_apache

- name: copy html file for site
  tags: apache,apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644



